"use strict";

const { openDatabase } = require("./database");
const { getAsset } = require("./assetRegistry");
const db = openDatabase();
db.exec(`CREATE TABLE IF NOT EXISTS account_staking_positions (staking_position_id INTEGER PRIMARY KEY AUTOINCREMENT, account_id TEXT NOT NULL, wallet_id INTEGER, asset_symbol TEXT NOT NULL, amount REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(account_id, wallet_id, asset_symbol)); CREATE TABLE IF NOT EXISTS staking_events (event_id TEXT PRIMARY KEY, account_id TEXT NOT NULL, wallet_id INTEGER, asset_symbol TEXT NOT NULL, event_type TEXT NOT NULL, amount REAL NOT NULL, block_number INTEGER, payload_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS staking_checkpoints (source TEXT PRIMARY KEY, block_number INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
function assertMock() { if (String(process.env.PERPSIA_STAKING_MODE || "mock").toLowerCase() !== "mock") throw new Error("Staking writes are disabled until the audited production contract is configured."); }
function amount(value) { const parsed = Number(value); if (!Number.isFinite(parsed) || parsed <= 0) throw new Error("Staking amount must be positive."); return parsed; }
function getStakingState(accountId, assetSymbol = "PERPSIA") { const rows = db.prepare("SELECT * FROM account_staking_positions WHERE account_id = ? AND asset_symbol = ? AND status = 'active'").all(String(accountId), String(assetSymbol).toUpperCase()); return { mode: String(process.env.PERPSIA_STAKING_MODE || "mock"), asset: getAsset(assetSymbol), positions: rows, totalStaked: rows.reduce((sum, row) => sum + Number(row.amount), 0) }; }
function applyStake(accountId, walletId, value, type) { assertMock(); const delta = amount(value); const asset = getAsset("PERPSIA"); const current = db.prepare("SELECT * FROM account_staking_positions WHERE account_id = ? AND wallet_id IS ? AND asset_symbol = ?").get(String(accountId), walletId ?? null, asset.symbol); const next = Number(current?.amount || 0) + (type === "stake" ? delta : -delta); if (next < 0) throw new Error("Cannot unstake more than the current mock stake."); db.prepare(`INSERT INTO account_staking_positions(account_id,wallet_id,asset_symbol,amount,status,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(account_id,wallet_id,asset_symbol) DO UPDATE SET amount=excluded.amount,status=excluded.status,updated_at=CURRENT_TIMESTAMP`).run(String(accountId), walletId ?? null, asset.symbol, next, next > 0 ? "active" : "inactive"); return getStakingState(accountId); }
function stakeMock(accountId, walletId, value) { return applyStake(accountId, walletId, value, "stake"); }
function unstakeMock(accountId, walletId, value) { return applyStake(accountId, walletId, value, "unstake"); }
function ingestStakingEvent(event = {}) { const result = db.prepare("INSERT OR IGNORE INTO staking_events(event_id,account_id,wallet_id,asset_symbol,event_type,amount,block_number,payload_json) VALUES(?,?,?,?,?,?,?,?)").run(String(event.eventId), String(event.accountId), event.walletId ?? null, String(event.assetSymbol || "PERPSIA").toUpperCase(), String(event.eventType || "stake"), amount(event.amount), event.blockNumber ?? null, JSON.stringify(event.payload || {})); return { applied: result.changes > 0, eventId: String(event.eventId) }; }
function updateCheckpoint(source, blockNumber) { db.prepare("INSERT INTO staking_checkpoints(source,block_number,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(source) DO UPDATE SET block_number=excluded.block_number,updated_at=CURRENT_TIMESTAMP").run(String(source), Number(blockNumber)); return db.prepare("SELECT * FROM staking_checkpoints WHERE source = ?").get(String(source)); }
module.exports = { getStakingState, ingestStakingEvent, stakeMock, unstakeMock, updateCheckpoint };
